#!/bin/sh
fslsplit $1
fslmerge -t nodif vol0000 vol0016 vol0031 vol0048 vol0064;
rm vol*
#rm vol0000.nii.gz vol0009.nii.gz vol0018.nii.gz vol0027.nii.gz vol0036.nii.gz vol0045.nii.gz vol0054.nii.gz
#rm vol0063.nii.gz
#fslmerge -t dif vol*
#rm vol*
#fslmerge -t reorgdata nodif dif 
